const PRODUCTS = [
  {
    id: 'deconstructed-bomber',
    name: 'Reconstructed Leather Patchwork Bomber Jacket',
    category: 'Tops',
    price: 320,
    notForSale: true,
    oneOfOne: true,
    origin: 'Made in Spain / Finland',
    images: [
      './assets/photos/PRODUCTS/Deconstructesd Bomber Jacket/1.jpg',
      './assets/photos/PRODUCTS/Deconstructesd Bomber Jacket/1.png',
      './assets/photos/PRODUCTS/Deconstructesd Bomber Jacket/3.png',
      './assets/photos/PRODUCTS/Deconstructesd Bomber Jacket/4.png',
      './assets/photos/PRODUCTS/Deconstructesd Bomber Jacket/5.png',
      './assets/photos/PRODUCTS/Deconstructesd Bomber Jacket/6.png',
    ],
    description: 'A one-of-a-kind reconstructed bomber built from patchworked leather panels, with exposed seams and raw-edge detailing. A unique archive piece — available by inquiry only.',
    material: 'Reconstructed Leather Patchwork',
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
  },
  {
    id: '3d-panel-bomber',
    name: '3D Panel Cropped Bomber Jacket',
    category: 'Tops',
    price: 340,
    images: [
      './assets/photos/PRODUCTS/3D Panel Bomber Jacket - Look 3 Top/24.jpg',
      './assets/photos/PRODUCTS/3D Panel Bomber Jacket - Look 3 Top/3DFit.png',
      './assets/photos/PRODUCTS/3D Panel Bomber Jacket - Look 3 Top/1_VSCO 3.JPG',
      './assets/photos/PRODUCTS/3D Panel Bomber Jacket - Look 3 Top/2_VSCO 3.JPG',
    ],
    description: 'Structured bomber with dimensional panel construction. Each seam is engineered for a sculptural, three-dimensional effect when worn.',
    material: '70% Polyester 30% Cotton',
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
  },
  {
    id: 'phyllite-jacket',
    name: 'Phyllite Jacket',
    category: 'Tops',
    price: 290,
    images: [
      './assets/photos/home/denim-feature-01.jpg',
      './assets/photos/PRODUCTS/DENIM1 - Lorimer Womens Wax Coated Denim Jacket/IMG_9001.JPG',
      './assets/photos/PRODUCTS/DENIM1 - Lorimer Womens Wax Coated Denim Jacket/IMG_9163.jpg',
      './assets/photos/PRODUCTS/DENIM1 - Lorimer Womens Wax Coated Denim Jacket/IMG_9180.JPG',
      './assets/photos/PRODUCTS/DENIM1 - Lorimer Womens Wax Coated Denim Jacket/IMG_9182.JPG',
    ],
    description: 'Classic denim jacket treated with a matte wax finish for a distinct texture and weather resistance. Fitted silhouette with raw hem.',
    material: '100% Cotton Denim / Wax Coated',
    sizes: ['XS', 'S', 'M', 'L'],
  },
  {
    id: 'lorimer-selvedge-denim',
    name: 'Lorimer Selvedge Denim — Blue',
    category: 'Bottoms',
    colorway: 'Blue',
    price: 80,
    images: [
      './assets/photos/home/denim-feature-02.jpg',
      './assets/photos/PRODUCTS/DENIM1 - Lorimer Womens Wax Coated Denim Jacket/DENIM1_SelvedgeDenim.JPG',
    ],
    description: 'Lorimer selvedge denim cut with a clean, structured silhouette and considered finishing throughout. Waxed and fabric-painted by hand — each pair develops its own character with wear.',
    material: 'Waxed / Fabric-Painted Selvedge Denim',
    sizes: ['30×30', '30×32', '32×30', '32×32', '32×34', '34×32', '34×34'],
  },
  {
    id: 'lorimer-selvedge-denim-black',
    name: 'Lorimer Selvedge Denim — Black',
    category: 'Bottoms',
    colorway: 'Black',
    price: 80,
    images: [
      './assets/photos/PRODUCTS/DENIM1 - Lorimer Womens Wax Coated Denim Jacket/DENIM1_SelvedgeDenim.JPG',
      './assets/photos/home/denim-feature-02.jpg',
    ],
    description: 'Lorimer selvedge denim in black — cut with a clean, structured silhouette and considered finishing throughout. Waxed and fabric-painted by hand, developing its own character with wear.',
    material: 'Waxed / Fabric-Painted Selvedge Denim',
    sizes: ['30×30', '30×32', '32×30', '32×32', '32×34', '34×32', '34×34'],
  },
  {
    id: 'reconstructed-button-up-1',
    name: 'Reconstructed Button Up Shirt 001',
    category: 'Tops',
    price: 185,
    images: [
      './assets/photos/PRODUCTS/Reconstructed Button Up 1/10.jpg',
      './assets/photos/PRODUCTS/Reconstructed Button Up 1/IMG_6238.JPG',
      './assets/photos/PRODUCTS/Reconstructed Button Up 1/IMG_6251.JPG',
      './assets/photos/PRODUCTS/Reconstructed Button Up 1/IMG_6328.JPG',
      './assets/photos/PRODUCTS/Reconstructed Button Up 1/IMG_6352.JPG',
    ],
    description: 'The first in our Reconstructed series. A deconstructed shirt form reimagined with displaced panels and asymmetrical placket.',
    material: '100% Cotton Poplin',
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
  },
  {
    id: 'reconstructed-button-up-2',
    name: 'Reconstructed Button Up Shirt 002',
    category: 'Tops',
    price: 185,
    images: [
      './assets/photos/PRODUCTS/Reconstructed Button Up 2/8.jpg',
      './assets/photos/PRODUCTS/Reconstructed Button Up 2/IMG_6539.JPG',
      './assets/photos/PRODUCTS/Reconstructed Button Up 2/IMG_6699.JPG',
      './assets/photos/PRODUCTS/Reconstructed Button Up 2/IMG_6712.JPG',
    ],
    description: 'The second iteration. Contrast fabric insert at yoke with a relaxed, oversized body. Multi-directional seaming throughout.',
    material: '100% Cotton Poplin / Deadstock Twill',
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
  },
  {
    id: 'university-striped-sweatshirt',
    name: 'University of Lorimer Striped Sweatshirt',
    category: 'Tops',
    price: 210,
    images: [
      './assets/photos/PRODUCTS/University of Lorimer Striped Sweatshirt - Look 2 Top/20.jpg',
      './assets/photos/PRODUCTS/University of Lorimer Striped Sweatshirt - Look 2 Top/1_VSCO 2.JPG',
      './assets/photos/PRODUCTS/University of Lorimer Striped Sweatshirt - Look 2 Top/2_VSCO 2.JPG',
    ],
    description: 'Collegiate-inspired sweatshirt with hand-applied stripe detailing. Relaxed boxy fit with ribbed cuffs and hem.',
    material: '80% Cotton 20% Polyester Fleece',
    sizes: ['S', 'M', 'L', 'XL'],
  },
  {
    id: 'zip-up-top',
    name: '1/3 Zip Up Top',
    category: 'Tops',
    price: 195,
    images: [
      './assets/photos/PRODUCTS/1-3%20Zip%20Up%20Top%20-%20Look%205%20Top/18.jpg',
      './assets/photos/PRODUCTS/1-3%20Zip%20Up%20Top%20-%20Look%205%20Top/2_VSCO%205.JPG',
      './assets/photos/PRODUCTS/1-3%20Zip%20Up%20Top%20-%20Look%205%20Top/IMG_0584_VSCO.JPG',
    ],
    description: 'Quarter-zip with elongated body and dropped shoulder. Clean minimal construction with matte hardware.',
    material: '95% Cotton 5% Elastane',
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
  },
  {
    id: 'asymmetrical-white-top',
    name: 'Asymmetrical White Top',
    category: 'Tops',
    price: 165,
    images: [
      './assets/photos/PRODUCTS/Asymmetrical White Top - Look 4 Top/22.jpg',
      './assets/photos/PRODUCTS/Asymmetrical White Top - Look 4 Top/IMG_0655_VSCO.JPG',
      './assets/photos/PRODUCTS/Asymmetrical White Top - Look 4 Top/IMG_0671_VSCO.JPG',
      './assets/photos/PRODUCTS/Asymmetrical White Top - Look 4 Top/IMG_0686_VSCO.JPG',
    ],
    description: 'Draped asymmetric hem in a lightweight cotton weave. Single shoulder construction with raw-finished edges.',
    material: '100% Cotton',
    sizes: ['XS', 'S', 'M', 'L'],
  },
  {
    id: 'westworld-button-up',
    name: 'Westworld',
    category: 'Tops',
    price: 175,
    images: [
      './assets/photos/PRODUCTS/Westworld Short Sleeve Button Up/3.jpg',
      './assets/photos/PRODUCTS/Westworld Short Sleeve Button Up/IMG_2947.jpeg',
      './assets/photos/PRODUCTS/Westworld Short Sleeve Button Up/IMG_2953.jpeg',
      './assets/photos/PRODUCTS/Westworld Short Sleeve Button Up/IMG_2957.jpeg',
      './assets/photos/PRODUCTS/Westworld Short Sleeve Button Up/IMG_2958.jpeg',
    ],
    description: 'Camp collar short sleeve with wide-set buttons. Relaxed straight hem. Wears clean tucked or untucked.',
    material: '100% Viscose',
    sizes: ['S', 'M', 'L', 'XL'],
  },
  {
    id: 'zip-up-utility-vest',
    name: 'Zip Up Utility Vest',
    category: 'Tops',
    price: 220,
    images: [
      './assets/photos/PRODUCTS/Zip Up Utility Vest/2.jpg',
    ],
    description: 'Technical utility vest with asymmetric zip and multiple panel seams. Slim structured fit.',
    material: '65% Polyester 35% Cotton',
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
  },
  {
    id: 'dual-texture-knit-vest',
    name: 'Dual Texture Knit Vest',
    category: 'Tops',
    price: 200,
    images: [
      './assets/photos/PRODUCTS/Dual Texture Knit Vest - Look 1 Top/16.jpg',
      './assets/photos/PRODUCTS/Dual Texture Knit Vest - Look 1 Top/1_VSCO.JPG',
    ],
    description: 'Contrast-knit vest combining two distinct knit textures in a single garment. Body-skimming silhouette.',
    material: '60% Wool 40% Acrylic',
    sizes: ['XS', 'S', 'M', 'L'],
  },
  {
    id: 'layered-denim-jeans',
    name: 'Layered Distressed Jeans',
    category: 'Bottoms',
    price: 245,
    images: [
      './assets/photos/PRODUCTS/Layered Denim Distressed Jeans/4.jpg',
      './assets/photos/PRODUCTS/Layered Denim Distressed Jeans/IMG_7844.JPG',
      './assets/photos/PRODUCTS/Layered Denim Distressed Jeans/IMG_7858.JPG',
      './assets/photos/PRODUCTS/Layered Denim Distressed Jeans/IMG_7877.JPG',
      './assets/photos/PRODUCTS/Layered Denim Distressed Jeans/IMG_8039.JPG',
    ],
    description: 'Straight-leg jeans with layered fabric panels at the outer leg. Heavy distressing throughout. Five-pocket construction.',
    material: '100% Cotton Denim 12oz',
    sizes: ['26', '27', '28', '29', '30', '32'],
  },
  {
    id: 'layered-denim-shorts',
    name: 'Layered Distressed Shorts',
    category: 'Bottoms',
    price: 195,
    images: [
      './assets/photos/PRODUCTS/Layerered Denim Distressed Shorts/6.jpg',
      './assets/photos/PRODUCTS/Layerered Denim Distressed Shorts/IMG_7641.JPG',
      './assets/photos/PRODUCTS/Layerered Denim Distressed Shorts/IMG_7679.JPG',
      './assets/photos/PRODUCTS/Layerered Denim Distressed Shorts/IMG_7700.JPG',
      './assets/photos/PRODUCTS/Layerered Denim Distressed Shorts/IMG_7762.JPG',
    ],
    description: 'Cut from the same heavy denim as the jeans. Layered hem detailing with raw-cut panels.',
    material: '100% Cotton Denim 12oz',
    sizes: ['26', '27', '28', '29', '30'],
  },
  {
    id: 'westworld-straight-jeans',
    name: 'Westworld Straight Leg Jeans',
    category: 'Bottoms',
    price: 235,
    images: [
      './assets/photos/PRODUCTS/Westworld Straight Leg Jeans/7.jpg',
    ],
    description: 'Straight-leg denim with a restrained Westworld construction and a clean full-length line.',
    material: '100% Cotton Denim',
    sizes: ['26', '27', '28', '29', '30', '32'],
  },
  {
    id: 'adjustable-button-trousers',
    name: 'Adjustable Button Trousers',
    category: 'Bottoms',
    price: 215,
    images: [
      './assets/photos/PRODUCTS/Adjustable Button Trousers - Look 1 Bottoms/17.jpg',
      './assets/photos/PRODUCTS/Adjustable Button Trousers - Look 1 Bottoms/2_VSCO.JPG',
    ],
    description: 'Wide-leg trousers with button-adjustable waistband for a custom fit. Pleated front, clean back.',
    material: '100% Wool Blend',
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
  },
  {
    id: 'mens-straight-trousers',
    name: "Men's Straight Cut Trousers",
    category: 'Bottoms',
    price: 215,
    images: [
      './assets/photos/PRODUCTS/Mens Straight Cut Trousers - Look 2 Bottoms/21.jpg',
    ],
    description: 'Tailored straight-leg trousers in a mid-weight fabric. Clean silhouette with side and back pockets.',
    material: '55% Polyester 45% Viscose',
    sizes: ['28', '30', '32', '34', '36'],
  },
  {
    id: 'denim-leather-trousers',
    name: 'Denim & Leather Trousers',
    category: 'Bottoms',
    price: 265,
    images: [
      './assets/photos/PRODUCTS/Denim and Leather Trousers - Look 3 Bottoms/25.jpg',
    ],
    description: 'Hybrid construction combining denim and leather panels. Straight leg with contrast seaming throughout.',
    material: 'Denim / Genuine Leather Panels',
    sizes: ['26', '28', '30', '32'],
  },
  {
    id: 'reinforced-pinstripe-trousers',
    name: 'Reinforced Pinstripe Trousers',
    category: 'Bottoms',
    price: 235,
    images: [
      './assets/photos/PRODUCTS/Reinforced Pinstripe Trousers/12.jpg',
    ],
    description: 'Classic pinstripe in a reinforced technical fabric. Straight cut with side adjusters and flat-front finish.',
    material: '100% Wool Pinstripe',
    sizes: ['28', '30', '32', '34'],
  },
  {
    id: 'womens-wide-trousers',
    name: "Women's Wide Cut Trousers",
    category: 'Bottoms',
    price: 215,
    images: [
      './assets/photos/PRODUCTS/Womens Wide Cut Trousers - Look 5 Bottoms/19.jpg',
      './assets/photos/PRODUCTS/Womens Wide Cut Trousers - Look 5 Bottoms/16.png',
    ],
    description: 'Fluid wide-leg trouser with high rise and full-length inseam. Drapes cleanly from hip to floor.',
    material: '100% Viscose',
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
  },
  {
    id: 'overlapped-fray-skirt',
    name: 'Overlapped Fray Skirt',
    category: 'Bottoms',
    price: 195,
    images: [
      './assets/photos/PRODUCTS/Overlapped Fray Skirt/14.jpg',
      './assets/photos/PRODUCTS/Overlapped Fray Skirt/IMG_2981.jpeg',
      './assets/photos/PRODUCTS/Overlapped Fray Skirt/IMG_3029.jpeg',
      './assets/photos/PRODUCTS/Overlapped Fray Skirt/9.png',
    ],
    description: 'Wrap skirt with overlapping frayed panels. Mid-length silhouette with raw edge treatment.',
    material: '100% Cotton',
    sizes: ['XS', 'S', 'M', 'L'],
  },
  {
    id: 'white-layered-skirt',
    name: 'White Layered Texture Skirt',
    category: 'Bottoms',
    price: 185,
    images: [
      './assets/photos/PRODUCTS/White Layered Texture Skirt - Look 4 Bottom/23.jpg',
      './assets/photos/PRODUCTS/White Layered Texture Skirt - Look 4 Bottom/Skirtt.png',
    ],
    description: 'Textured A-line skirt with layered hem detail. Clean waistband with concealed zip.',
    material: '100% Cotton Jacquard',
    sizes: ['XS', 'S', 'M', 'L'],
  },
  {
    id: 'upcycled-two-piece',
    name: 'Upcycled Two Piece Suit',
    category: 'Accessories',
    price: 450,
    images: [
      './assets/photos/PRODUCTS/Upcycled Two Piece Suit/15.jpg',
      './assets/photos/PRODUCTS/Upcycled Two Piece Suit/Upsycle.Photo.Best.jpg',
    ],
    description: 'One-of-a-kind suit constructed entirely from upcycled and deadstock fabrics. No two pieces alike.',
    material: 'Upcycled Mixed Fabrics',
    sizes: ['S', 'M', 'L'],
  },
  {
    id: 'trigall-dress',
    name: 'Trigall Dress',
    category: 'Dresses',
    price: 380,
    images: [
      './assets/photos/PRODUCTS/Trigall Dress/13.jpg',
      './assets/photos/PRODUCTS/Trigall Dress/Pic1.Edited.jpg',
      './assets/photos/PRODUCTS/Trigall Dress/Pic2.Edited.jpg',
    ],
    description: 'A sculptural dress with triangulated panels and architectural draping. Midi length with structured bodice.',
    material: '100% Polyester Crepe',
    sizes: ['XS', 'S', 'M', 'L'],
  },
  {
    id: 'ss24-dress',
    name: 'S/S24 Dress',
    category: 'Dresses',
    price: 360,
    images: [
      './assets/photos/PRODUCTS/SS24 Dress/26.jpg',
      './assets/photos/PRODUCTS/SS24 Dress/IMG_0716_VSCO.JPG',
      './assets/photos/PRODUCTS/SS24 Dress/IMG_0742_VSCO.JPG',
    ],
    description: 'The SS24 signature piece. Fluid column silhouette with asymmetric neckline and minimal construction.',
    material: '100% Silk Charmeuse',
    sizes: ['XS', 'S', 'M', 'L'],
  },
].map(product => ({
  ...product,
  available: ['phyllite-jacket', 'lorimer-selvedge-denim', 'lorimer-selvedge-denim-black'].includes(product.id),
}));

if (typeof module !== 'undefined') module.exports = PRODUCTS;
